added new buildspec in main to work on muli folder deployment.

diff --git a/buildspecnew.yaml b/buildspecnew.yaml
--- a/buildspecnew.yaml
+++ b/buildspecnew.yaml
@@ -5,37 +5,22 @@ phases:
       docker: 18
   pre_build:
     commands:
-      - text_file_path=file.txt
-      # Check if the text file is provided as an argument
       - |
-        if [ "$#" -ne 1 ]; then
-          echo "Usage: $0 <text_file>";
-          exit 1;
+        if [ ! -f "$text_file" ]; then
+          echo "Text file not found at $text_file"
+          exit 1
         fi
-      # Read each line from the text file and perform actions
+      ls
+      echo "---------------------------"
       - |
-        while IFS= read -r directory_name; do
-          # Skip empty lines or lines starting with a comment (#)
-          if [[ "$directory_name" == "" || "$directory_name" == \#* ]]; then
-            continue;
-          fi
-          # Print the current directory name
-          echo "Entering directory: $directory_name"
-          # Change to the specified directory
-          cd "$directory_name"
-          # List files in the current directory
-          ls
-          # Print the current working directory
-          pwd
-          # Print contents of text.txt if it exists
-          if [ -f "text.txt" ]; then
-            echo "Contents of text.txt:"
-            cat "text.txt"
-            echo "---------------------------"
-          else
-            echo "text.txt not found in $directory_name"
-          fi
-          # Additional commands to execute within the directory can be added here
-          # Change back to the original directory
+        while IFS= read -r LINE || [ -n "$LINE" ]; do
+          echo "Line from file: $LINE";
+          echo "---------------------------"
+          echo "---------------------------"
+          cd $LINE
+          echo "Contents of text.txt:"
+          cat "text.txt"
+          echo "---------------------------"
+          echo "---------------------------"
           cd ..
-        done < "$1"
+        done < "$text_file"
